// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PorcinoRemoto.App.Persistencia;

#nullable disable

namespace PorcinoRemoto.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PorcinoRemoto.App.Dominio.Direccion", b =>
                {
                    b.Property<int>("DireccionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DireccionID"), 1L, 1);

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DireccionID");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("PorcinoRemoto.App.Dominio.HistoriaClinica", b =>
                {
                    b.Property<int>("HistoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoriaID"), 1L, 1);

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.HasKey("HistoriaID");

                    b.ToTable("HistoriasClinicas");
                });

            modelBuilder.Entity("PorcinoRemoto.App.Dominio.Persona", b =>
                {
                    b.Property<string>("PersonaID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DireccionID")
                        .HasColumnType("int");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonaID");

                    b.HasIndex("DireccionID");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("PorcinoRemoto.App.Dominio.Porcino", b =>
                {
                    b.Property<int>("PorcinoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PorcinoID"), 1L, 1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HistoriaID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropietarioID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Raza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PorcinoID");

                    b.HasIndex("HistoriaID");

                    b.HasIndex("PropietarioID");

                    b.ToTable("Porcinos");
                });

            modelBuilder.Entity("PorcinoRemoto.App.Dominio.Propietario", b =>
                {
                    b.Property<string>("PersonaID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonaID");

                    b.ToTable("Propietarios");
                });

            modelBuilder.Entity("PorcinoRemoto.App.Dominio.Veterinario", b =>
                {
                    b.Property<string>("PersonaID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TarjetaProfesional")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonaID");

                    b.ToTable("Veterinarios");
                });

            modelBuilder.Entity("PorcinoRemoto.App.Dominio.Visita", b =>
                {
                    b.Property<int>("VisitaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitaID"), 1L, 1);

                    b.Property<string>("EstadoAnimo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaVisita")
                        .HasColumnType("datetime2");

                    b.Property<double>("FrecuenciaCardiaca")
                        .HasColumnType("float");

                    b.Property<double>("FrecuenciaRespiratoria")
                        .HasColumnType("float");

                    b.Property<int>("HistoriaID")
                        .HasColumnType("int");

                    b.Property<string>("MedicamentosFormulados")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<int?>("PorcinoID")
                        .HasColumnType("int");

                    b.Property<double>("Temperatura")
                        .HasColumnType("float");

                    b.Property<string>("VeterinarioID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("VisitaID");

                    b.HasIndex("HistoriaID");

                    b.HasIndex("PorcinoID");

                    b.HasIndex("VeterinarioID");

                    b.ToTable("Visitas");
                });

            modelBuilder.Entity("PorcinoRemoto.App.Dominio.Persona", b =>
                {
                    b.HasOne("PorcinoRemoto.App.Dominio.Direccion", "Direccion")
                        .WithMany()
                        .HasForeignKey("DireccionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("PorcinoRemoto.App.Dominio.Porcino", b =>
                {
                    b.HasOne("PorcinoRemoto.App.Dominio.HistoriaClinica", "HistoriaClinica")
                        .WithMany()
                        .HasForeignKey("HistoriaID");

                    b.HasOne("PorcinoRemoto.App.Dominio.Propietario", "Propietario")
                        .WithMany("Porcinos")
                        .HasForeignKey("PropietarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoriaClinica");

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("PorcinoRemoto.App.Dominio.Propietario", b =>
                {
                    b.HasOne("PorcinoRemoto.App.Dominio.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("PorcinoRemoto.App.Dominio.Veterinario", b =>
                {
                    b.HasOne("PorcinoRemoto.App.Dominio.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("PorcinoRemoto.App.Dominio.Visita", b =>
                {
                    b.HasOne("PorcinoRemoto.App.Dominio.HistoriaClinica", "HistoriaClinica")
                        .WithMany("Visitas")
                        .HasForeignKey("HistoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PorcinoRemoto.App.Dominio.Porcino", "Porcino")
                        .WithMany("Visitas")
                        .HasForeignKey("PorcinoID");

                    b.HasOne("PorcinoRemoto.App.Dominio.Veterinario", "Veterinario")
                        .WithMany("Visitas")
                        .HasForeignKey("VeterinarioID");

                    b.Navigation("HistoriaClinica");

                    b.Navigation("Porcino");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("PorcinoRemoto.App.Dominio.HistoriaClinica", b =>
                {
                    b.Navigation("Visitas");
                });

            modelBuilder.Entity("PorcinoRemoto.App.Dominio.Porcino", b =>
                {
                    b.Navigation("Visitas");
                });

            modelBuilder.Entity("PorcinoRemoto.App.Dominio.Propietario", b =>
                {
                    b.Navigation("Porcinos");
                });

            modelBuilder.Entity("PorcinoRemoto.App.Dominio.Veterinario", b =>
                {
                    b.Navigation("Visitas");
                });
#pragma warning restore 612, 618
        }
    }
}
